### ISSUE TITLE
run ./run_loongarch.sh时缺少依赖libfuse3.so.3解决方法

### ISSUE THREAD

**Issue by jiangtao-ucas** [foxsen/qemu-loongarch-runenv#2]
There maybe appear an error: + ./qemu-system-loongarch64 -m 4G -smp 1 -bios ./loongarch_bios_0310_debug.bin -kernel ./vmlinux -initrd busybox-rootfs.img -append 'root=/dev/ram console=ttyS0,115200 rdinit=/init' -vga none -nographic
./qemu-system-loongarch64: error while loading shared libraries: libfuse3.so.3: cannot open shared object file: No such file or directory

The solution is to install  [libfuse3.so.3](https://www.devmanuals.net/install/ubuntu/ubuntu-20-04-focal-fossa/installing-libfuse3-3-on-ubuntu20-04.html).

**Comment by foxsen** [comment]
Yes, qemu rely on some libraries.  Due to OS difference, the provided binary might not work due to unmetable dependencies(e.g. your OS might have libfuse3.so.2 instead of libfuse3.so.3). You can build a copy of qemu from source by yourself in this case.
